/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.complex_schema;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class unsignedLongList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"unsignedLongList\",\"namespace\":\"avro.complex_schema\",\"fields\":[{\"name\":\"unsignedLongList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"scale\":0,\"precision\":34}},\"doc\":\"Simple type null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Simple type null */
  @Deprecated public java.util.List<java.nio.ByteBuffer> unsignedLongList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public unsignedLongList() {}

  /**
   * All-args constructor.
   */
  public unsignedLongList(java.util.List<java.nio.ByteBuffer> unsignedLongList) {
    this.unsignedLongList = unsignedLongList;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return unsignedLongList;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: unsignedLongList = (java.util.List<java.nio.ByteBuffer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'unsignedLongList' field.
   * Simple type null   */
  public java.util.List<java.nio.ByteBuffer> getUnsignedLongList() {
    return unsignedLongList;
  }

  /**
   * Sets the value of the 'unsignedLongList' field.
   * Simple type null   * @param value the value to set.
   */
  public void setUnsignedLongList(java.util.List<java.nio.ByteBuffer> value) {
    this.unsignedLongList = value;
  }

  /** Creates a new unsignedLongList RecordBuilder */
  public static avro.complex_schema.unsignedLongList.Builder newBuilder() {
    return new avro.complex_schema.unsignedLongList.Builder();
  }
  
  /** Creates a new unsignedLongList RecordBuilder by copying an existing Builder */
  public static avro.complex_schema.unsignedLongList.Builder newBuilder(avro.complex_schema.unsignedLongList.Builder other) {
    return new avro.complex_schema.unsignedLongList.Builder(other);
  }
  
  /** Creates a new unsignedLongList RecordBuilder by copying an existing unsignedLongList instance */
  public static avro.complex_schema.unsignedLongList.Builder newBuilder(avro.complex_schema.unsignedLongList other) {
    return new avro.complex_schema.unsignedLongList.Builder(other);
  }
  
  /**
   * RecordBuilder for unsignedLongList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<unsignedLongList>
    implements org.apache.avro.data.RecordBuilder<unsignedLongList> {

    private java.util.List<java.nio.ByteBuffer> unsignedLongList;

    /** Creates a new Builder */
    private Builder() {
      super(avro.complex_schema.unsignedLongList.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.complex_schema.unsignedLongList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.unsignedLongList)) {
        this.unsignedLongList = data().deepCopy(fields()[0].schema(), other.unsignedLongList);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing unsignedLongList instance */
    private Builder(avro.complex_schema.unsignedLongList other) {
            super(avro.complex_schema.unsignedLongList.SCHEMA$);
      if (isValidValue(fields()[0], other.unsignedLongList)) {
        this.unsignedLongList = data().deepCopy(fields()[0].schema(), other.unsignedLongList);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'unsignedLongList' field */
    public java.util.List<java.nio.ByteBuffer> getUnsignedLongList() {
      return unsignedLongList;
    }
    
    /** Sets the value of the 'unsignedLongList' field */
    public avro.complex_schema.unsignedLongList.Builder setUnsignedLongList(java.util.List<java.nio.ByteBuffer> value) {
      validate(fields()[0], value);
      this.unsignedLongList = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'unsignedLongList' field has been set */
    public boolean hasUnsignedLongList() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'unsignedLongList' field */
    public avro.complex_schema.unsignedLongList.Builder clearUnsignedLongList() {
      unsignedLongList = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public unsignedLongList build() {
      try {
        unsignedLongList record = new unsignedLongList();
        record.unsignedLongList = fieldSetFlags()[0] ? this.unsignedLongList : (java.util.List<java.nio.ByteBuffer>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
