/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.complex_schema.enums;  
@SuppressWarnings("all")
/** Enumeration of symbols in {urn:avro:complex_schema}avroEnum */
@org.apache.avro.specific.AvroGenerated
public enum avroEnum { 
  xml, json, avro, thrift, protobuf, rest_li  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"avroEnum\",\"namespace\":\"avro.complex_schema.enums\",\"doc\":\"Enumeration of symbols in {urn:avro:complex_schema}avroEnum\",\"symbols\":[\"xml\",\"json\",\"avro\",\"thrift\",\"protobuf\",\"rest_li\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
